### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by paulobocanegra** [ForgoneReality/dissonance#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by paulobocanegra** [comment]
There is no division from Backend and Frontend, one MVP is the whole backend-frontend of a feature:
Servers, Accounts, and Messages (July 7-10)

Servers is one MVP:
Users can create servers
Users can edit servers
Users can delete servers
etc

Accounts is another MVP, and so is Messages.

**Comment by ForgoneReality** [comment]
I think i fixed it?

**Comment by paulobocanegra** [comment]
We need a few more updates:

Expand on User Auth (your 3rd MVP), there is more than just a Demo account, here is an example: 
https://github.com/appacademy/bluebird/wiki/mvp-list

General Project Setup is not an MVP, check the link as a reference.

Expand on Messages. is it CRUD? if so, let's make bullet points for each aspect of CRUD.

Styling is not an MVP. Check same link for inspiration.

**Comment by ForgoneReality** [comment]
Okay, thanks!

Hmm okay I wanted to put the styling there anyway to match my intended to-do timeline, I like doing the cosmetic stuff last. I'll add some of my optional stuff to replace it, cant think of anything else

**Comment by paulobocanegra** [comment]
Let's remove this bulletpoint: Not doing group chats because I'm lazy and I don't think it's that important (its functionality is pretty much covered by servers already).

The wiki page is not for your TA's but for other engineers/recruiters that will be looking at your repo. We don't want to disclose that.
