### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by paulobocanegra** [ForgoneReality/dissonance#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by paulobocanegra** [comment]
under the table users, what is the purpose of user type? What types of users are you thinking on implementing?

**Comment by paulobocanegra** [comment]
limit on body is definitely a good idea. Discord has a limit of 2000 characters.

**Comment by ForgoneReality** [comment]
Hi Paulo! 

I'm thinking of four major ones: Website Admin (which is pretty much just me I guess), Nitro (able to post animated stuff and some other stuff, this is a bonus), Regular, and Demo. The distinction between regular and demo might not exist, not sure yet. I might not need usertypes at all depending on how far into the project I get

**Comment by paulobocanegra** [comment]
Don't make a difference between the Demo and a regular user. The demo user is for recruiters to use all features of your application without having to create an account. 

I would leave making an admin user for after the project is done. If you are the admin, you can always jump on VStudio and make any changes on the codebase. I highly recommend you to only have one type of user for the purpose of building the fullstack in 2 weeks. 

Although it may seem like a lot of time, about half of it will be spent on styling.

**Comment by paulobocanegra** [comment]
When you add the db constraint related to "limit on body?" , remove the question from the Wiki Page (it is under the messages table).
